In [1]:
import pybullet as p
import time
from pybullet_sim_panda.bullet_robot import *
import numpy as np

pybullet build time: Oct 11 2021 20:59:39


In [2]:
uid = p.connect(p.GUI)
p.setAdditionalSearchPath(pybullet_data.getDataPath()) # for loading plane

# Simulation configuration
rate = 240.
p.setTimeStep(1/rate)
p.resetSimulation() #init
p.setGravity(0, 0, -9.8) #set gravity

# Load
plane_id = p.loadURDF("plane.urdf") # load plane
panda = PandaBullet(p) # load robot

### Real-time Simulation

In [3]:
p.setRealTimeSimulation(True)

In [4]:
panda.control_joint_positions([0,0,0,-1,2,1,2])

In [8]:
states = panda.get_all_states()
pos = states["position"]
vel = states["velocity"]
acc = np.zeros(len(states["velocity"])).tolist()

In [ ]:
panda.control_joint_positions([0,0,0,0,0,1,-2])

In [17]:
coriolis_gravity_force = p.calculateInverseDynamics(panda.robot, pos, vel, acc)
coriolis_gravity_force = [coriolis_gravity[i]for i in panda._arm_joints]

In [18]:
jacobian = panda.get_body_jacobian()

In [31]:
clear(p)

In [22]:
view_pose(p, panda.get_ee_pose())

[0, 1, 2]

In [39]:
ee_target_pose = np.eye(4)
ee_target_pose[:3,-1] = np.array([0.1, 0.1, 0.0])
ee_target_pose = panda.get_ee_pose() @ ee_target_pose
ee_curr_pose = panda.get_ee_pose()

In [40]:
ee_target_pose

array([[ 0.66501558, -0.37887113, -0.64359222,  0.30498169],
       [ 0.5611406 , -0.31518432,  0.76536271,  0.22993406],
       [-0.49282401, -0.87012385,  0.00299749,  0.79677699],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [41]:
ee_curr_pose

array([[ 0.66501558, -0.37887113, -0.64359222,  0.27636724],
       [ 0.5611406 , -0.31518432,  0.76536271,  0.20533844],
       [-0.49282401, -0.87012385,  0.00299749,  0.93307178],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [44]:
trans_err = ee_target_pose[:3,-1] - ee_curr_pose[:3,-1]

In [ ]:
rot_err = ee_target_pose.T @ ee_curr_pose

In [4]:
class Base():
    @staticmethod
    def a():
        return 3
class Foo(Base):
    def __init__(self):
        pass
    
    def b(self):
        return self.a()

In [5]:
a = Foo()

In [8]:
import  numpy as np

In [14]:
np.eye(3) @ np.array([1,0,0])

array([1., 0., 0.])

In [11]:
len()

4

In [ ]:
ee_target_pose

In [34]:
R = panda.get_ee_pose()[:3,:3]

In [30]:
view_pose(p, ee_target_pose)

[6, 7, 8]

### Simulation in while loop (Torque/Position control)

In [ ]:
while(1):
    panda.set_control_mode(mode_str="position")
    panda.control_joint_positions([0,0,0,0,0,1,1])
    #panda.set_control_mode(mode_str="torque")
    #panda.control_joint_torques([0,0,0,0,0,1,100])
    
    p.stepSimulation()
    time.sleep(1/rate)